export enum ActivityAction {
  // Authentication events
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_REGISTER = "USER_REGISTER",
  PASSWORD_RESET = "PASSWORD_RESET",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  MFA_ENABLED = "MFA_ENABLED",
  MFA_DISABLED = "MFA_DISABLED",

  // Resource actions
  RESOURCE_CREATE = "RESOURCE_CREATE",
  RESOURCE_READ = "RESOURCE_READ",
  RESOURCE_UPDATE = "RESOURCE_UPDATE",
  RESOURCE_DELETE = "RESOURCE_DELETE",

  // Administrative actions
  SETTINGS_CHANGE = "SETTINGS_CHANGE",
  USER_PERMISSION_CHANGE = "USER_PERMISSION_CHANGE",
  SYSTEM_CONFIGURATION = "SYSTEM_CONFIGURATION",

  // API usage
  API_REQUEST = "API_REQUEST",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Security events
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  BLOCKED_REQUEST = "BLOCKED_REQUEST",

  // Feature usage
  FEATURE_USAGE = "FEATURE_USAGE",
  EXPORT_DATA = "EXPORT_DATA",
  IMPORT_DATA = "IMPORT_DATA",
}

export enum ActivitySeverity {
  DEBUG = "DEBUG",
  INFO = "INFO",
  NOTICE = "NOTICE",
  WARNING = "WARNING",
  ERROR = "ERROR",
  CRITICAL = "CRITICAL",
}

export enum ActivityCategory {
  AUTHENTICATION = "AUTHENTICATION",
  AUTHORIZATION = "AUTHORIZATION",
  DATA_ACCESS = "DATA_ACCESS",
  CONFIGURATION = "CONFIGURATION",
  SECURITY = "SECURITY",
  PERFORMANCE = "PERFORMANCE",
  FEATURE_USAGE = "FEATURE_USAGE",
  API_USAGE = "API_USAGE",
  SYSTEM = "SYSTEM",
}

